### PR TITLE
addedSupportInformation

### PR DESCRIPTION
**Pull request by FoxieHazmat**
Tweaked the README to urge users to bring up issues in the Scripts' repositories first.

### CODE REVIEW

**Comment by Jarli01** [comment]
I think detail would be better placed in the troubleshooting doc, and from the readme we can put a link to that document.

**Comment by Jarli01** [comment]
And while the goal is to ensure people go to the correct channel first, even we need them to fill out an issue with the details listed in the issues template.

**Comment by FoxieHazmat** [comment]
Interesting. I am on it.
Any other frequent issues that I should add?

**Comment by FoxieHazmat** [comment]
Let me know what you think.

**Comment by FoxieHazmat** [comment]
Thanks for bearing with me here. Still learning GH's meta. 

I was pointing to my repo to make sure everything was working correctly. Didn't know about the link directly to create a new issue, though.

**Comment by Jarli01** [comment]
Thank you for the additions.

**Pull request merged**
