### PR TITLE
Direct people to this GH news issues page first rather than leaving t…

### PR DESCRIPTION
**Pull request by Jarli01**
As a means of hopefully avoiding more banners/warnings/odd modifications from the dev team and a recent conversation with Olivier this change is being pushed as a means to get users of this script to come here for help first and the team here can elevate to vatesfr if so required.

We should also push this change with the update script as well.

### CODE REVIEW

**Comment by Danp2** [comment]
Again... I'll take a look when I can. I believe that Olivier is too quick to dismiss issues due to the use of a 3rd party script. The script is essentially automating their manual process, but I guess YMMV.

P.S. I can approach him to see if he would allow a section in the XCP forums for 3rd party products.

**Comment by Jarli01** [comment]
@Danp2 any comments on this?

**Comment by Danp2** [comment]
I haven't tested it, but I don't have any issues with the "concept". Due to the influx in new issues, you may want to review / update the issues template accordingly.

**Comment by Danp2** [comment]
Oh... and don't forget that these "patches" need to carry over to the update script as well.

**Comment by Danp2** [comment]
@Jarli01 I thought you had changed your intention on implementing this after speaking with Olivier

**Comment by Jarli01** [comment]
It only makes sense to drive people to this repo first and if it's a dev issue upstream we would escalate. Do you disagree?

**Comment by Jarli01** [comment]
Closing this for now, will reconsider if this issue persists.

**Pull request closed without merging**
