### PR TITLE
Direct Import

### PR DESCRIPTION
**Pull request by Jarli01**
Replicates the direct import process

### CODE REVIEW

**Comment by Danp2** [comment]
@Jarli01 Should this be closed?

**Comment by Jarli01** [comment]
If it worked for you it can be merged

**Comment by Jarli01** [comment]
Oh it removed the entire or... Gah

**Comment by Jarli01** [comment]
Still need the source file to exist so no don't close, I'll resolve myself.

**Comment by Danp2** [comment]
How is this file different from the xoce script?

**Comment by Jarli01** [comment]
I made a clean file name that worked in my lab, the older scriptay not work. Additionally the be needs to be sorted out

**Pull request closed without merging**
