### PR TITLE
Check distro and install multiverse repo if = Ubuntu

### PR DESCRIPTION
**Pull request by bnrstnr**
Tested on clean Debian 9.5 and clean Ubuntu with, and without, multiverse already installed.

### CODE REVIEW

**Comment by Danp2** [comment]
This looks fine to me. I would suggest that we also change the line 

```/usr/bin/apt-get install --yes build-essential redis-server libpng-dev git python-minimal libvhdi-utils nfs-common```

 by adding this to the end 

```|| echo "Aborting due to failure to install dependencies. Please see troubleshooting guide." && exit```

**Comment by bnrstnr** [comment]
Good call @Danp2 
I'll add this to the PR

**Comment by bnrstnr** [comment]
Hmm, for some reason this isn't working now

**Comment by bnrstnr** [comment]
I thought I tested with @Danp2's stuff, but apparently I didn't. For some reason it just stops later in the build. I've removed his code for now and will play with it tomorrow morning some and do another PR if I can get it working. 

This PR should work as it is right now though.

**Pull request merged**
